/** @type {import("../verity_knowledge_data.js").KnowledgeEntry[]} */
export const MINECRAFT_KNOWLEDGE = [
	{ patterns: [/\bwhat is a creeper\b/], keywords: ["creeper", "mob", "explode", "ssss"], answers: ["Creepers silently approach and explode — iconic, terrifying, born from a coding mistake. Keep distance or shield-block."] },
	{ patterns: [/\bwhat is an enderman\b/], keywords: ["enderman", "teleport", "tall", "block"], answers: ["Endermen are tall teleporting mobs that get angry if you look at their face — and relocate your blocks."] },
	{ patterns: [/\bwhat is a zombie\b/], keywords: ["zombie", "undead", "mob", "night"], answers: ["Zombies are common undead that burn in sunlight — they break doors on hard and can drown into drowned."] },
	{ patterns: [/\bwhat is a skeleton\b/], keywords: ["skeleton", "bow", "arrow", "bone"], answers: ["Skeletons shoot bows — strafe them. They burn in sun; helmets delay it. Bone meal comes from their drops."] },
	{ patterns: [/\bwhat is a spider\b/], keywords: ["spider", "climb", "web", "mob"], answers: ["Spiders climb walls and are neutral in light — cave spiders are smaller, poisonous, and live in mineshafts."] },
	{ patterns: [/\bwhat is a witch\b/], keywords: ["witch", "potion", "hut", "swamp"], answers: ["Witches throw harmful potions and drink healing — find them in swamps or raids. Drops include redstone and glowstone."] },
	{ patterns: [/\bwhat is a blaze\b/], keywords: ["blaze", "nether", "rod", "fire"], answers: ["Blazes float in Nether fortresses shooting fireballs — blaze rods power brewing stands."] },
	{ patterns: [/\bwhat is a ghast\b/], keywords: ["ghast", "nether", "cry", "fireball"], answers: ["Ghasts are huge floating Nether mobs — their fireballs hurt but you can bat them back. Tearful sounds included."] },
	{ patterns: [/\bwhat is a wither skeleton\b/], keywords: ["wither", "skeleton", "skull", "sword"], answers: ["Wither skeletons in Nether fortresses inflict wither — their skulls are rare drops needed to summon the Wither boss."] },
	{ patterns: [/\bwhat is the wither\b/], keywords: ["wither", "boss", "skull", "soul"], answers: ["The Wither is a boss built from soul sand and skulls — shoots wither skulls, drops a nether star for beacons."] },
	{ patterns: [/\bwhat is the ender dragon\b/], keywords: ["ender", "dragon", "boss", "end"], answers: ["The Ender Dragon guards the End — destroy end crystals on obsidian pillars, then finish the fight for a dragon egg."] },
	{ patterns: [/\bwhat is the warden\b/], keywords: ["warden", "deep", "dark", "sculk"], answers: ["The Warden is a blind deep-dark boss that hears vibrations — don't fight it, sneak or distract with projectiles."] },
	{ patterns: [/\bwhat is sculk\b/], keywords: ["sculk", "sensor", "shrieker", "warden"], answers: ["Sculk spreads in the deep dark — sensors detect sound, shriekers summon Wardens. Silk touch or embrace the horror."] },
	{ patterns: [/\bwhat is a piglin\b/], keywords: ["piglin", "gold", "barter", "nether"], answers: ["Piglins love gold armor and barter — don't open chests near them. Brutes don't barter; they just hurt."] },
	{ patterns: [/\bwhat is a hoglin\b/], keywords: ["hoglin", "crimson", "nether", "food"], answers: ["Hoglins are crimson forest beasts — good food source in the Nether, zombify outside it."] },
	{ patterns: [/\bwhat is a villager\b/], keywords: ["villager", "trade", "emerald", "job"], answers: ["Villagers trade by profession — librarian for enchanted books, farmer for food. Protect them from zombies at night."] },
	{ patterns: [/\bwhat is an iron golem\b/], keywords: ["iron", "golem", "village", "protect"], answers: ["Iron golems defend villages — you can build one with iron blocks and a pumpkin. Roses optional."] },
	{ patterns: [/\bwhat is a phantom\b/], keywords: ["phantom", "sleep", "insomnia", "wing"], answers: ["Phantoms spawn when you skip sleep for three nights — swoop down from the sky. Beds solve the problem."] },
	{ patterns: [/\bwhat is a shulker\b/], keywords: ["shulker", "end", "city", "levitation"], answers: ["Shulkers hide in End city boxes shooting levitation bullets — their shells make awesome storage blocks."] },
	{ patterns: [/\bwhat is an elytra\b/], keywords: ["elytra", "glide", "wings", "end"], answers: ["Elytra are wings from End ships — glide with fireworks for boost. Repair with phantom membranes."] },
	{ patterns: [/\bwhat is a beacon\b/], keywords: ["beacon", "nether", "star", "buff"], answers: ["Beacons need a nether star and pyramid of mineral blocks — grant speed, haste, resistance, jump boost, strength, or regeneration."] },
	{ patterns: [/\bwhat is a conduit\b/], keywords: ["conduit", "ocean", "heart", "sea"], answers: ["Conduits powered by nautilus shells and prismarine give underwater breathing and damage nearby mobs — guardian tech."] },
	{ patterns: [/\bwhat is netherite\b/], keywords: ["netherite", "upgrade", "smithing", "ancient"], answers: ["Netherite is top-tier gear — upgrade diamond at a smithing table with ancient debris smelted to ingots. Lava-resistant."] },
	{ patterns: [/\bwhat is ancient debris\b/], keywords: ["ancient", "debris", "nether", "y16"], answers: ["Ancient debris spawns low in the Nether — mine around Y=15 with beds or TNT carefully. Smelt to netherite scrap."] },
	{ patterns: [/\bwhat is a stronghold\b/], keywords: ["stronghold", "portal", "eye", "ender"], answers: ["Strongholds hide End portals — throw eyes of ender to find one, fill the frame, jump in."] },
	{ patterns: [/\bwhat is a bastion\b/], keywords: ["bastion", "remnant", "piglin", "nether"], answers: ["Bastion remnants are piglin fortresses in the Nether — gold blocks, magma cubes, brutes, and treasure if you're brave."] },
	{ patterns: [/\bwhat is an end city\b/], keywords: ["end", "city", "ship", "elytra"], answers: ["End cities spawn after defeating the dragon — shulkers, purpur, and ships with elytra far from the main island."] },
	{ patterns: [/\bwhat is a raid\b/], keywords: ["raid", "pillager", "bad", "omen"], answers: ["Raids start when you enter a village with Bad Omen — waves of pillagers, evokers, ravagers. Win for discounts and totems."] },
	{ patterns: [/\bwhat is a totem\b/, /\btotem of undying\b/], keywords: ["totem", "undying", "evoker", "cheat"], answers: ["Totem of Undying saves you from fatal damage once — hold in hand or off-hand. Evokers drop them in raids."] },
	{ patterns: [/\bwhat is a trident\b/], keywords: ["trident", "drowned", "riptide", "channeling"], answers: ["Tridents are thrown weapons from drowned — enchant with Loyalty, Riptide, Channeling, or Impaling."] },
	{ patterns: [/\bwhat is redstone\b/], keywords: ["redstone", "dust", "signal", "circuit"], answers: ["Redstone carries power levels 0–15 — comparators, repeaters, pistons. Minecraft's wiring for farms and doors."] },
	{ patterns: [/\bwhat is a hopper\b/], keywords: ["hopper", "item", "sort", "chest"], answers: ["Hoppers suck items from above and push into containers below — item transport backbone for farms."] },
	{ patterns: [/\bwhat is an observer\b/], keywords: ["observer", "detect", "block", "update"], answers: ["Observers output a pulse when the block in front updates — great for automatic farms and flying machines."] },
	{ patterns: [/\bwhat is enchanting\b/], keywords: ["enchant", "table", "lapis", "xp"], answers: ["Enchanting spends XP and lapis at a table — bookshelves boost level cap. Anvil combines and repairs."] },
	{ patterns: [/\bwhat is brewing\b/], keywords: ["brew", "potion", "stand", "blaze"], answers: ["Brewing uses a stand, blaze powder, and awkward potions — add nether wart first, then ingredients for effects."] },
	{ patterns: [/\bwhat is a chunk\b/], keywords: ["chunk", "16", "load", "border"], answers: ["A chunk is 16×16 blocks column — world loads and unloads by chunks. Mob farms care about chunk borders."] },
	{ patterns: [/\bwhat is spawn proofing\b/], keywords: ["spawn", "proof", "light", "mob"], answers: ["Spawn-proof by light level 7+ on surfaces or slabs/carpets — stops hostile spawns in farms and bases."] },
	{ patterns: [/\bwhat is light level\b/], keywords: ["light", "level", "spawn", "torch"], answers: ["Light 0–15 — hostiles spawn at 0 on blocks. Torches are 14, sunlight 15. F3 or light blocks help you check."] },
	{ patterns: [/\bwhat is hardcore\b/], keywords: ["hardcore", "one", "life", "permadeath"], answers: ["Hardcore is one life only — die and you're locked to spectator. Java tradition; Bedrock has similar options in worlds."] },
	{ patterns: [/\bwhat is a behavior pack\b/], keywords: ["behavior", "pack", "bp", "addon"], answers: ["Behavior packs change game logic — entities, items, scripts. Pair with a resource pack for visuals. You're in one now."] },
	{ patterns: [/\bwhat is a resource pack\b/], keywords: ["resource", "pack", "rp", "texture"], answers: ["Resource packs change models, textures, sounds, and UI — the art layer on top of behavior packs."] },
	{ patterns: [/\bwhat is script api\b/, /\bwhat is the script api\b/], keywords: ["script", "api", "javascript", "addon"], answers: ["Script API runs JavaScript in behavior packs — @minecraft/server for gameplay, events, entities, and world logic."] },
	{ patterns: [/\bbedrock vs java\b/, /\bdifference bedrock java\b/], keywords: ["bedrock", "java", "difference", "edition"], answers: ["Bedrock is cross-platform C++ with marketplace; Java is PC mod-heavy. Redstone, combat, and farms differ — both are Minecraft."] },
	{
		patterns: [
			/\bwho is herobrine\b/,
			/\bwhat is herobrine\b/,
			/\bis herobrine real\b/,
			/\bdoes herobrine exist\b/,
			/\bhave you seen herobrine\b/,
		],
		keywords: ["herobrine", "real", "exist", "creepypasta", "myth"],
		answers: [
			"Herobrine is Minecraft's most famous creepypasta — a white-eyed Steve from an old community story. He isn't in vanilla Minecraft. Probably.",
		],
	},
	{
		patterns: [
			/\bhow (?:do i|to|can i) summon herobrine\b/,
			/\bcan you summon herobrine\b/,
		],
		keywords: ["herobrine", "summon", "spawn", "totem"],
		answers: [
			"You can't summon Herobrine in vanilla Minecraft. Any ritual you saw needs a mod, addon, command setup, or someone trying to scare you.",
		],
	},
	{
		patterns: [
			/\bwho is entity 303\b/,
			/\bwhat is entity 303\b/,
			/\bis entity 303 real\b/,
			/\bdoes entity 303 exist\b/,
		],
		keywords: ["entity", "303", "creepypasta", "hacker", "myth"],
		answers: [
			"Entity 303 is a fan-made Minecraft creepypasta about a mysterious hacker. It isn't a real vanilla entity.",
		],
	},
	{
		patterns: [
			/\bwho is null\b/,
			/\bwhat is null\b/,
			/\bis null real\b/,
			/\bdoes null exist\b/,
		],
		keywords: ["null", "minecraft", "creepypasta", "entity", "myth"],
		answers: [
			"Null is another community-made Minecraft horror myth — not a real vanilla mob. Empty darkness just gives people ideas.",
		],
	},
	{
		patterns: [
			/\bwhat is seed 666\b/,
			/\bis seed 666 haunted\b/,
			/\bis minecraft seed 666 cursed\b/,
		],
		keywords: ["seed", "666", "haunted", "cursed", "myth"],
		answers: [
			"Seed 666 isn't secretly haunted. It's an ordinary world seed; scary videos usually use editing, mods, addons, or staged events.",
		],
	},
	{
		patterns: [
			/\bwhat is the aether\b/,
			/\bhow (?:do i|to) make an aether portal\b/,
			/\bis the aether portal real\b/,
		],
		keywords: ["aether", "portal", "glowstone", "water", "mod"],
		answers: [
			"The Aether is a famous Minecraft mod dimension. A glowstone-and-water portal does nothing in vanilla unless a mod or addon adds it.",
		],
	},
	{
		patterns: [
			/\bwhat are the far lands\b/,
			/\bwhat is the far lands\b/,
			/\bdo the far lands exist\b/,
			/\bhow (?:do i|to) find the far lands\b/,
		],
		keywords: ["far", "lands", "terrain", "generation", "bug"],
		answers: [
			"The Far Lands were extreme terrain caused by old generation precision bugs millions of blocks from spawn. Modern versions removed the classic form.",
		],
	},
	{ patterns: [/\bwho is notch\b/], keywords: ["notch", "markus", "persson", "creator"], answers: ["Notch (Markus Persson) created Minecraft — sold Mojang to Microsoft in 2014. The cube legend started in 2009."] },
	{ patterns: [/\bwho owns minecraft\b/, /\bwho owns mojang\b/], keywords: ["microsoft", "mojang", "owns", "minecraft"], answers: ["Microsoft owns Mojang and Minecraft since 2014 — still updated across Bedrock and Java teams."] },
	{ patterns: [/\bwhat is a seed\b/], keywords: ["seed", "world", "generate", "random"], answers: ["A world seed is a number or text that deterministically shapes terrain — same seed, same geography. Speedrunners memorize good ones."] },
	{ patterns: [/\bhow to find diamonds\b/, /\bwhere are diamonds\b/], keywords: ["diamond", "find", "y", "mine"], answers: ["Diamonds spawn best around Y=-59 in 1.18+ — strip mine at that level, bring iron or better, watch lava."] },
	{ patterns: [/\bhow to get netherite\b/], keywords: ["netherite", "get", "debris", "upgrade"], answers: ["Mine ancient debris in the Nether low Y, smelt to scrap, combine 4 scrap + 4 gold for ingot, smithing table upgrade diamond gear."] },
	{ patterns: [/\bhow to beat the ender dragon\b/], keywords: ["beat", "dragon", "ender", "crystals"], answers: ["Shoot end crystals on pillars first — bow or build up. Then melee the dragon when it perches. Beds work in Java; careful in Bedrock."] },
	{ patterns: [/\bhow to cure zombie villager\b/], keywords: ["cure", "zombie", "villager", "golden"], answers: ["Splash weakness potion on zombie villager, feed golden apple, wait — cured villagers discount trades and remember your heroism."] },
	{ patterns: [/\bwhat is a biome\b/], keywords: ["biome", "climate", "terrain", "spawn"], answers: ["Biomes are regional climate zones — plains, desert, jungle, etc. Each has unique blocks, mobs, and vibes."] },
	{ patterns: [/\bwhat is the deep dark\b/], keywords: ["deep", "dark", "ancient", "city"], answers: ["The Deep Dark is a sculk biome far underground — silent, dark, ancient cities, and Wardens. Bring wool or stay quiet."] },
	{ patterns: [/\bwhat is an ancient city\b/], keywords: ["ancient", "city", "deep", "dark"], answers: ["Ancient cities are massive Deep Dark structures — loot, sculk, and one wrong step wakes the Warden. Sneak is survival."] },
	{ patterns: [/\bwhat is the nether\b/], keywords: ["nether", "dimension", "hell", "portal"], answers: ["The Nether is a hellish dimension — 8 blocks overworld = 1 nether for travel. Fortresses, bastions, piglins, lava oceans."] },
	{ patterns: [/\bwhat is the end\b/], keywords: ["end", "dimension", "dragon", "void"], answers: ["The End is a void dimension with end stone islands — defeat the dragon to access gateways and cities. Chorus fruit grows here."] },
	{ patterns: [/\bwhat is chorus fruit\b/], keywords: ["chorus", "fruit", "teleport", "end"], answers: ["Chorus fruit teleports you randomly when eaten — farm chorus plants on end stone for food and popped chorus crafting."] },
	{ patterns: [/\bwhat is a golden apple\b/, /\bgolden apple\b/], keywords: ["golden", "apple", "gapple", "absorption"], answers: ["Golden apples give absorption and regeneration — enchanted ones are stronger from villager trades or dungeon loot."] },
	{ patterns: [/\bwhat is mending\b/], keywords: ["mending", "enchant", "xp", "repair"], answers: ["Mending repairs gear from XP orbs you collect — best enchant in the game. Fish or librarian trade for the book."] },
	{ patterns: [/\bwhat is silk touch\b/], keywords: ["silk", "touch", "enchant", "block"], answers: ["Silk Touch lets you mine blocks as themselves — ice, glass, ore blocks, sculk. No fortune on same item."] },
	{ patterns: [/\bwhat is fortune\b/], keywords: ["fortune", "enchant", "drops", "ore"], answers: ["Fortune multiplies ore and crop drops — III on pickaxe is diamond farmer's friend. Incompatible with silk touch."] },
	{ patterns: [/\bwhat is looting\b/], keywords: ["looting", "enchant", "sword", "drops"], answers: ["Looting on swords increases mob drops — more blaze rods, wither skulls slightly less painful to grind."] },
	{ patterns: [/\bwhat is efficiency\b/], keywords: ["efficiency", "enchant", "mine", "fast"], answers: ["Efficiency digs faster — V on a netherite pickaxe melts stone. Haste beacon stacks for insane speed."] },
	{ patterns: [/\bwhat is a shield\b/], keywords: ["shield", "block", "banner", "creeper"], answers: ["Shields block frontal damage including creeper explosions — add banners for style. Axes can disable them."] },
	{ patterns: [/\bwhat is a crossbow\b/], keywords: ["crossbow", "piercing", "multishot", "quick"], answers: ["Crossbows load arrows or fireworks — enchant Piercing, Multishot, Quick Charge. Pillagers brought the trend."] },
	{ patterns: [/\bwhat is a grindstone\b/], keywords: ["grindstone", "repair", "disenchant", "village"], answers: ["Grindstones repair gear and remove enchantments — village job site for weaponsmith."] },
	{ patterns: [/\bwhat is a smithing table\b/], keywords: ["smithing", "table", "template", "trim"], answers: ["Smithing tables upgrade gear to netherite and apply armor trims — netherite templates from bastions or ancient cities."] },
	{ patterns: [/\bwhat is an armor trim\b/], keywords: ["armor", "trim", "smithing", "pattern"], answers: ["Armor trims are cosmetic patterns applied at smithing tables — find templates in structures, flex without extra protection."] },
];
