/** @type {import("../verity_knowledge_data.js").KnowledgeEntry[]} */
export const MORE_MC_KNOWLEDGE = [
	{ patterns: [/\bhow to craft a bed\b/], keywords: ["craft", "bed", "sleep", "wool"], answers: ["Three wool on top row, three planks below in a crafting table. Colors match wool."] },
	{ patterns: [/\bhow to craft torches\b/], keywords: ["torch", "craft", "coal", "stick"], answers: ["Coal or charcoal above a stick — gives 4 torches. Light level 14."] },
	{ patterns: [/\bhow to craft a pickaxe\b/], keywords: ["pickaxe", "craft", "mine", "tool"], answers: ["Three material top row, two sticks vertical center — wood, stone, iron, diamond, netherite."] },
	{ patterns: [/\bhow to craft a sword\b/], keywords: ["sword", "craft", "weapon", "fight"], answers: ["Material on top center, same below, stick at bottom center. Sharpness helps later."] },
	{ patterns: [/\bhow to craft an axe\b/], keywords: ["axe", "craft", "chop", "wood"], answers: ["Two material top left diagonal, stick below — faster wood, decent weapon."] },
	{ patterns: [/\bhow to craft a shovel\b/], keywords: ["shovel", "craft", "dig", "dirt"], answers: ["One material top center, two sticks below — dirt, sand, gravel go fast."] },
	{ patterns: [/\bhow to craft a hoe\b/], keywords: ["hoe", "craft", "farm", "till"], answers: ["Two material top row corners, sticks center below — tills dirt for crops."] },
	{ patterns: [/\bhow to craft a bucket\b/], keywords: ["bucket", "craft", "water", "lava"], answers: ["Iron ingot in V shape — holds water, lava, milk, axolotls, fish."] },
	{ patterns: [/\bhow to craft a furnace\b/], keywords: ["furnace", "craft", "smelt", "cobble"], answers: ["Eight cobblestone in square ring — smelts ore, cooks food, makes charcoal."] },
	{ patterns: [/\bhow to craft a crafting table\b/], keywords: ["crafting", "table", "bench", "planks"], answers: ["Four planks in a 2x2 square in inventory — unlocks 3x3 recipes."] },
	{ patterns: [/\bhow to craft chest\b/], keywords: ["chest", "craft", "storage", "wood"], answers: ["Eight planks in square ring — 27 slots. Two side by side makes a double chest."] },
	{ patterns: [/\bhow to craft boat\b/], keywords: ["boat", "craft", "water", "travel"], answers: ["Five planks in U shape — fastest early ocean travel. Chest boat stores items."] },
	{ patterns: [/\bhow to craft bow\b/], keywords: ["bow", "craft", "arrow", "shoot"], answers: ["Three sticks and three string in pattern — needs arrows. Infinity enchant is luxury."] },
	{ patterns: [/\bhow to craft arrows\b/], keywords: ["arrow", "craft", "flint", "feather"], answers: ["Flint top, stick middle, feather bottom — one each makes 4 arrows."] },
	{ patterns: [/\bhow to craft shield\b/], keywords: ["shield", "craft", "block", "iron"], answers: ["Planks fill grid except top center iron ingot — block frontal damage."] },
	{ patterns: [/\bhow to make iron\b/, /\bhow to smelt iron\b/], keywords: ["iron", "smelt", "ore", "ingot"], answers: ["Smelt raw iron or iron ore in furnace — ore needs silk touch or fortune on stone pick+."] },
	{ patterns: [/\bhow to get food\b/, /\bwhat food\b/], keywords: ["food", "eat", "hunger", "farm"], answers: ["Kill animals, farm wheat and bread, fish, cook meat for best saturation. Golden carrots endgame."] },
	{ patterns: [/\bhow to breed animals\b/], keywords: ["breed", "animal", "farm", "wheat"], answers: ["Feed breeding food — wheat cows, seeds chickens, carrots pigs, berries foxes. Hearts mean baby soon."] },
	{
		patterns: [/\bwhat is a cow\b/, /\bwhat(?:'s| is) cow\b/, /\btell me about cows?\b/],
		keywords: ["cow", "beef", "leather", "milk", "moo"],
		answers: [
			"Cows are passive mobs — wheat to breed, bucket for milk, beef and leather when you kill them. Classic farm starter.",
			"Cow. Easy food and leather. Hold wheat and they'll follow you home.",
		],
	},
	{
		patterns: [/\bwhat does a cow (sound like|say|go)\b/, /\bcow sound\b/],
		keywords: ["cow", "moo", "sound"],
		answers: [
			"A cow goes moo. Ask me to play the cow sound if you want to hear it.",
			"Moo. That's the whole review. Say play cow sound and I'll do it.",
		],
	},
	{ patterns: [/\bhow to tame a wolf\b/], keywords: ["tame", "wolf", "dog", "bone"], answers: ["Feed bones until hearts — collar, follows, attacks what you hit."] },
	{ patterns: [/\bhow to tame a cat\b/], keywords: ["tame", "cat", "ocelot", "fish"], answers: ["Feed raw cod or salmon to stray cats — scares creepers when nearby."] },
	{ patterns: [/\bhow to find village\b/], keywords: ["find", "village", "villager", "trade"], answers: ["Explore plains, desert, savanna, taiga. Ask me to locate one — I can scan."] },
	{ patterns: [/\bhow to trade\b/, /\bhow do villagers trade\b/], keywords: ["trade", "villager", "emerald", "job"], answers: ["Right-click villager with job site block nearby — emeralds for goods. Zombify cure for discounts."] },
	{ patterns: [/\bwhat is a librarian\b/], keywords: ["librarian", "villager", "book", "enchant"], answers: ["Librarian trades enchanted books — lectern job site. Reset trades by break job block carefully."] },
	{ patterns: [/\bwhat is a farmer\b/], keywords: ["farmer", "villager", "crop", "food"], answers: ["Farmer trades crops and golden carrots — composter job site. Good for food economy."] },
	{ patterns: [/\bwhat is obsidian\b/], keywords: ["obsidian", "portal", "lava", "water"], answers: ["Obsidian forms when water hits lava source — diamond pick or better to mine. Portal frames need 10+."] },
	{ patterns: [/\bwhat is cobblestone\b/], keywords: ["cobble", "cobblestone", "stone", "mine"], answers: ["Mining stone with pickaxe drops cobble — building staple, furnace fuel for charcoal path."] },
	{ patterns: [/\bwhat is gravel\b/], keywords: ["gravel", "flint", "fall", "block"], answers: ["Gravel falls like sand — mine for flint for arrows. Found underground and beaches."] },
	{ patterns: [/\bwhat is sand\b/], keywords: ["sand", "glass", "desert", "fall"], answers: ["Sand falls and smelts to glass — deserts, beaches. Red sand in badlands."] },
	{ patterns: [/\bwhat is clay\b/], keywords: ["clay", "brick", "terracotta", "ball"], answers: ["Clay balls from mining clay blocks — smelt bricks or dye terracotta. Rivers and lush caves."] },
	{ patterns: [/\bwhat is wool\b/], keywords: ["wool", "sheep", "bed", "color"], answers: ["Shear sheep or combine string — beds need wool, 16 dye colors available."] },
	{ patterns: [/\bwhat is leather\b/], keywords: ["leather", "cow", "armor", "book"], answers: ["Cows and horses drop leather — armor, item frames, books with paper."] },
	{ patterns: [/\bwhat is paper\b/], keywords: ["paper", "sugar", "cane", "book"], answers: ["Three sugar cane in a row — books, maps, fireworks. Farm cane by water."] },
	{ patterns: [/\bwhat is sugar cane\b/], keywords: ["sugar", "cane", "reed", "farm"], answers: ["Grows on sand or dirt adjacent to water — up to 3 blocks. Paper and sugar source."] },
	{ patterns: [/\bwhat is bamboo\b/], keywords: ["bamboo", "jungle", "panda", "scaffold"], answers: ["Fast-growing jungle plant — pandas eat it, scaffolding fuel, sticks in bulk."] },
	{ patterns: [/\bwhat is kelp\b/], keywords: ["kelp", "ocean", "fuel", "dried"], answers: ["Underwater plant — dried kelp blocks as fuel, eat dried kelp for quick snack."] },
	{ patterns: [/\bwhat is a saddle\b/], keywords: ["saddle", "horse", "pig", "ride"], answers: ["Cannot craft in vanilla — dungeon, fishing, villager trade. Ride horses, pigs, striders."] },
	{ patterns: [/\bwhat is an anvil\b/], keywords: ["anvil", "repair", "enchant", "rename"], answers: ["Three iron blocks top, four ingots bottom plus center — repair gear, combine enchants, rename."] },
	{ patterns: [/\bwhat is lapis\b/], keywords: ["lapis", "enchant", "blue", "ore"], answers: ["Lapis lazuli from ore — required for enchanting table. Mine around Y 0 in 1.18+."] },
	{ patterns: [/\bwhat is emerald\b/], keywords: ["emerald", "village", "trade", "ore"], answers: ["Villager currency — also rare mountain ore. Trade farming beats mining usually."] },
	{ patterns: [/\bwhat is coal\b/], keywords: ["coal", "fuel", "torches", "ore"], answers: ["Common fuel and torch material — burns in furnace, torches with sticks."] },
	{ patterns: [/\bwhat is charcoal\b/], keywords: ["charcoal", "fuel", "smelt", "wood"], answers: ["Smelt logs in furnace — same fuel value as coal, renewable from trees."] },
	{ patterns: [/\bwhat is a spawn\b/], keywords: ["spawn", "respawn", "bed", "point"], answers: ["Where you appear — world spawn at start, bed sets personal respawn. Compass points world spawn."] },
	{ patterns: [/\bwhat is coordinates\b/, /\bwhat are coordinates\b/], keywords: ["coord", "xyz", "f3", "position"], answers: ["X east-west, Y height, Z north-south — F3 or settings show them. I read yours when asked."] },
	{ patterns: [/\bwhat is fall damage\b/], keywords: ["fall", "damage", "height", "land"], answers: ["Falling hurts after 3 blocks — water, hay, slime, slow falling negate. MLG water bucket classic."] },
	{ patterns: [/\bwhat is hunger effect\b/], keywords: ["hunger", "effect", "husk", "food"], answers: ["Hunger effect drains food bar faster — from husks. Eat more while active."] },
	{ patterns: [/\bwhat is poison\b/], keywords: ["poison", "effect", "cave", "spider"], answers: ["Poison damages over time but won't kill — half heart left. Milk cures. Cave spiders inflict it."] },
	{ patterns: [/\bwhat is wither effect\b/], keywords: ["wither", "effect", "black", "hearts"], answers: ["Wither turns hearts black and drains health — wither skeletons and wither boss. Golden apples help."] },
	{ patterns: [/\bhow to fly\b/, /\bcan i fly\b/], keywords: ["fly", "creative", "elytra", "spectator"], answers: ["Survival: elytra plus fireworks or slow falling. Creative and spectator fly free."] },
	{ patterns: [/\bhow to swim\b/], keywords: ["swim", "water", "drown", "bubble"], answers: ["Double tap forward underwater or hold sprint — bubbles run out without respiration enchant or doors trick."] },
];
