/** @type {import("../verity_knowledge_data.js").KnowledgeEntry[]} */
export const LIFE_KNOWLEDGE = [
	{ patterns: [/\bhow to tie\b/, /\bhow do i tie\b/], keywords: ["tie", "shoelace", "knot", "shoe"], answers: ["Cross laces, loop one, wrap the other around and pull through the hole. Bunny ears method works too."] },
	{ patterns: [/\bhow to boil an egg\b/, /\bhow do i boil\b/], keywords: ["boil", "egg", "cook", "water"], answers: ["Gentle boil 9–12 minutes for hard boiled. Ice bath after. Soft boil is about 6–7 minutes."] },
	{ patterns: [/\bhow to cook rice\b/], keywords: ["cook", "rice", "water", "pot"], answers: ["Rinse rice, 1:1.5 rice to water roughly, simmer covered low until absorbed. Rest 10 minutes."] },
	{ patterns: [/\bhow to make tea\b/], keywords: ["make", "tea", "hot", "water"], answers: ["Boil water, pour over tea bag or leaves, steep 3–5 minutes. Remove bag. Don't burn yourself."] },
	{ patterns: [/\bhow to wash hands\b/], keywords: ["wash", "hands", "soap", "hygiene"], answers: ["Wet, soap 20 seconds, scrub backs and between fingers, rinse, dry. Before food and after bathroom."] },
	{ patterns: [/\bhow to brush teeth\b/], keywords: ["brush", "teeth", "dental", "tooth"], answers: ["Twice daily, two minutes, small circles on all surfaces, floss, fluoride toothpaste."] },
	{ patterns: [/\bwhat is first aid\b/], keywords: ["first", "aid", "emergency", "injury"], answers: ["First aid is immediate care for injury — stop bleeding, CPR if trained, call emergency services for serious cases."] },
	{ patterns: [/\bwhat is cpr\b/], keywords: ["cpr", "cardiac", "chest", "compress"], answers: ["CPR is chest compressions and rescue breaths when someone's heart stops — get trained; it saves lives."] },
	{ patterns: [/\bwhat is a calorie\b/], keywords: ["calorie", "food", "energy", "diet"], answers: ["A calorie measures food energy — your body burns them for fuel. Balance in vs out for weight."] },
	{ patterns: [/\bwhat is protein\b/], keywords: ["protein", "muscle", "meat", "amino"], answers: ["Protein builds and repairs tissue — meat, eggs, beans, dairy. Cooked steak is endgame fuel here too."] },
	{ patterns: [/\bwhat is vitamin\b/, /\bwhat are vitamins\b/], keywords: ["vitamin", "nutrition", "health", "deficiency"], answers: ["Vitamins are nutrients needed in small amounts — A, B, C, D and more from varied diet or sun."] },
	{ patterns: [/\bwhat is exercise\b/], keywords: ["exercise", "workout", "fitness", "health"], answers: ["Exercise strengthens heart, muscles, and mood — walk, run, swim, whatever you'll actually do."] },
	{ patterns: [/\bwhat is meditation\b/], keywords: ["meditation", "mindful", "calm", "breathe"], answers: ["Meditation is focused attention practice — breath, stillness, less mental noise. No enchantment required."] },
	{ patterns: [/\bwhat is stress\b/], keywords: ["stress", "anxiety", "pressure", "tension"], answers: ["Stress is your body reacting to pressure — short bursts help; chronic stress hurts. Rest, talk, breathe."] },
	{ patterns: [/\bwhat is a bank\b/], keywords: ["bank", "money", "account", "loan"], answers: ["A bank stores money, lends, handles payments — savings accounts earn interest, loans cost interest."] },
	{ patterns: [/\bwhat is a loan\b/], keywords: ["loan", "borrow", "interest", "debt"], answers: ["A loan is borrowed money you repay with interest — mortgages, student loans, read terms carefully."] },
	{ patterns: [/\bwhat is tax\b/, /\bwhat are taxes\b/], keywords: ["tax", "government", "income", "pay"], answers: ["Taxes fund public services — roads, schools, healthcare. Rates and rules vary by country."] },
	{ patterns: [/\bwhat is a job\b/, /\bwhat is work\b/], keywords: ["job", "work", "career", "employ"], answers: ["A job is paid work — trade time and skill for money. Careers are long-term paths in a field."] },
	{ patterns: [/\bwhat is an interview\b/], keywords: ["interview", "job", "hire", "question"], answers: ["An interview is a meeting to assess fit for a job — prepare examples, ask questions, be on time."] },
	{ patterns: [/\bwhat is a resume\b/, /\bwhat is a cv\b/], keywords: ["resume", "cv", "job", "apply"], answers: ["A resume or CV lists your skills and experience for employers — clear, honest, one to two pages."] },
	{ patterns: [/\bwhat is homework\b/], keywords: ["homework", "school", "assignment", "study"], answers: ["Homework is school work done at home — reinforces class. Procrastination is the real boss fight."] },
	{ patterns: [/\bwhat is math\b/, /\bwhat is mathematics\b/], keywords: ["math", "mathematics", "number", "logic"], answers: ["Mathematics studies numbers, patterns, and logic — arithmetic to calculus. I can do basic arithmetic in chat."] },
	{ patterns: [/\bwhat is history\b/], keywords: ["history", "past", "event", "civilization"], answers: ["History is the study of past human events — causes, lessons, stories. Those who ignore it repeat it."] },
	{ patterns: [/\bwhat is geography\b/], keywords: ["geography", "map", "country", "land"], answers: ["Geography studies places — land, climate, people, borders. Maps beat wandering in the Nether."] },
	{ patterns: [/\bwhat is literature\b/], keywords: ["literature", "book", "novel", "read"], answers: ["Literature is written art — novels, poetry, drama exploring human experience across cultures."] },
	{ patterns: [/\bwhat is physics\b/], keywords: ["physics", "force", "energy", "motion"], answers: ["Physics studies matter, energy, and forces — motion, gravity, electricity. Minecraft simplifies most of it."] },
	{ patterns: [/\bwhat is chemistry\b/], keywords: ["chemistry", "element", "reaction", "molecule"], answers: ["Chemistry studies substances and reactions — atoms bonding, changing, exploding in labs with goggles."] },
	{ patterns: [/\bwhat is biology\b/], keywords: ["biology", "life", "organism", "cell"], answers: ["Biology studies living things — cells to ecosystems. You're a walking biology project."] },
	{ patterns: [/\bwhat is a map\b/], keywords: ["map", "direction", "navigation", "compass"], answers: ["A map represents geography — roads, terrain, labels. In-game maps need a cartography table."] },
	{ patterns: [/\bwhat is a compass\b/], keywords: ["compass", "north", "direction", "navigate"], answers: ["A compass needle points magnetic north — navigation since ancient China. Minecraft points to spawn."] },
	{ patterns: [/\bwhat is a clock\b/], keywords: ["clock", "time", "hour", "watch"], answers: ["A clock measures time — sundials to atomic clocks. Minecraft days are 20 real minutes."] },
	{ patterns: [/\bwhat is weather\b/], keywords: ["weather", "rain", "sun", "forecast"], answers: ["Weather is short-term atmosphere — rain, wind, temperature. Forecasts use science; I can read sky here."] },
	{ patterns: [/\bwhat is a storm\b/], keywords: ["storm", "thunder", "lightning", "rain"], answers: ["A storm brings heavy rain, wind, lightning — stay inside in real life. Charged creepers need lightning."] },
	{ patterns: [/\bwhat is lightning\b/], keywords: ["lightning", "thunder", "bolt", "electric"], answers: ["Lightning is massive electrical discharge in storms — thunder is the sound lag. Rods protect builds."] },
	{ patterns: [/\bwhat is a rainbow\b/], keywords: ["rainbow", "color", "light", "arc"], answers: ["A rainbow forms when sunlight refracts through water droplets — ROYGBIV arc after rain."] },
	{ patterns: [/\bwhat is a house\b/], keywords: ["house", "home", "shelter", "build"], answers: ["A house is shelter — walls, roof, safety. Your first dirt box counts."] },
	{ patterns: [/\bwhat is rent\b/], keywords: ["rent", "apartment", "landlord", "pay"], answers: ["Rent is payment to live in someone else's property — lease terms, deposit, monthly due date."] },
	{ patterns: [/\bwhat is electricity bill\b/, /\bwhat is a utility\b/], keywords: ["utility", "bill", "electric", "water"], answers: ["Utilities are services like power and water — monthly bills based on usage. Torches are free here."] },
	{ patterns: [/\bwhat is friendship\b/], keywords: ["friendship", "friend", "trust", "bond"], answers: ["Friendship is mutual care and trust over time — shared time, honesty, showing up. Worth more than loot."] },
	{ patterns: [/\bwhat is family\b/], keywords: ["family", "parent", "sibling", "relative"], answers: ["Family is kin by blood or choice — parents, siblings, partners, kids. Home is often who waits for you."] },
	{ patterns: [/\bwhat is respect\b/], keywords: ["respect", "kind", "polite", "honor"], answers: ["Respect is treating others with dignity — listen, don't harm, keep promises. Works in multiplayer too."] },
	{ patterns: [/\bwhat is honesty\b/], keywords: ["honesty", "truth", "lie", "trust"], answers: ["Honesty is telling the truth — builds trust. Lies are shortcuts that cost more later."] },
	{ patterns: [/\bwhat is patience\b/], keywords: ["patience", "wait", "calm", "slow"], answers: ["Patience is tolerating delay without anger — crops grow, ore takes time, answers come when ready."] },
	{ patterns: [/\bwhat is courage\b/], keywords: ["courage", "brave", "fear", "bold"], answers: ["Courage is acting despite fear — not absence of fear. First night in Minecraft is a tutorial."] },
	{ patterns: [/\bwhat is kindness\b/], keywords: ["kindness", "nice", "help", "care"], answers: ["Kindness is choosing to help and not harm — small acts compound. Feed a stray wolf energy."] },
	{ patterns: [/\bhow to be happy\b/], keywords: ["happy", "happiness", "joy", "feel"], answers: ["No single formula — connection, purpose, health, gratitude help. Also sleep and food. Seriously."] },
	{ patterns: [/\bhow to learn\b/, /\bhow do i learn\b/], keywords: ["learn", "study", "practice", "skill"], answers: ["Practice deliberately, sleep on it, teach others, fail and fix. Curiosity beats cramming long term."] },
	{ patterns: [/\bhow to focus\b/], keywords: ["focus", "concentrate", "distract", "attention"], answers: ["One task, phone away, short breaks, clear goal. Pomodoro: 25 minutes on, 5 off."] },
	{ patterns: [/\bwhat is password\b/, /\bwhat is a password\b/], keywords: ["password", "login", "security", "account"], answers: ["A password proves identity — long, unique, not shared. Use a manager; don't use 'password123'."] },
	{ patterns: [/\bwhat is phishing\b/], keywords: ["phishing", "scam", "email", "fake"], answers: ["Phishing fakes trusted messages to steal passwords — check sender, don't click weird links."] },
];
