import { answerWhoIsThatMob, answerSecretWho } from "../verity_lib.js";

/** @type {import("../verity_knowledge_data.js").KnowledgeEntry[]} */
export const CULTURE_KNOWLEDGE = [
	{ patterns: [/\bwhat is harry potter\b/], keywords: ["harry", "potter", "hogwarts", "wizard"], answers: ["Harry Potter is a fantasy book and film series by J.K. Rowling about a boy wizard at Hogwarts fighting Voldemort."] },
	{ patterns: [/\bwhat is star wars\b/], keywords: ["star", "wars", "jedi", "force"], answers: ["Star Wars is a sci-fi saga about the Force, Jedi, Sith, and galactic rebellion — films since 1977."] },
	{ patterns: [/\bwhat is marvel\b/, /\bwhat is the mcu\b/], keywords: ["marvel", "mcu", "avengers", "superhero"], answers: ["Marvel is a superhero comics universe — Iron Man, Spider-Man, Avengers. The MCU is the connected film series."] },
	{ patterns: [/\bwhat is batman\b/], keywords: ["batman", "bruce", "wayne", "gotham"], answers: ["Batman is DC's vigilante Bruce Wayne — no powers, just money, trauma, and gadgets in Gotham City."] },
	{ patterns: [/\bwhat is pokemon\b/, /\bwhat is pokémon\b/], keywords: ["pokemon", "pikachu", "trainer", "nintendo"], answers: ["Pokémon is Nintendo's franchise about catching and battling creatures — games, anime, cards since the 90s."] },
	{ patterns: [/\bwhat is roblox\b/], keywords: ["roblox", "game", "platform", "online"], answers: ["Roblox is a platform where users play and create games — huge with kids, millions of user-made experiences."] },
	{ patterns: [/\bwhat is fortnite\b/], keywords: ["fortnite", "battle", "royale", "epic"], answers: ["Fortnite is Epic's battle royale shooter with building — free to play, constant updates and crossovers."] },
	{ patterns: [/\bwhat is among us\b/], keywords: ["among", "us", "impostor", "crewmate"], answers: ["Among Us is a social deduction game — find the impostor on a spaceship before they eliminate the crew."] },
	{ patterns: [/\bwhat is disney\b/], keywords: ["disney", "mickey", "theme", "park"], answers: ["Disney is a media empire — animation, parks, Marvel, Star Wars. Mickey Mouse started it in 1928."] },
	{ patterns: [/\bwhat is anime\b/], keywords: ["anime", "japanese", "cartoon", "manga"], answers: ["Anime is Japanese animated storytelling — from kid shows to deep films. Often adapted from manga comics."] },
	{ patterns: [/\bwhat is manga\b/], keywords: ["manga", "comic", "japanese", "read"], answers: ["Manga are Japanese comics read right to left — source material for much anime."] },
	{ patterns: [/\bwhat is kpop\b/, /\bwhat is k-pop\b/], keywords: ["kpop", "korean", "music", "idol"], answers: ["K-pop is Korean pop music with polished groups, choreography, and global fandoms — BTS, Blackpink, and many more."] },
	{ patterns: [/\bwhat is christmas\b/], keywords: ["christmas", "december", "santa", "holiday"], answers: ["Christmas on December 25 celebrates the birth of Jesus for Christians — also gifts, trees, and family worldwide."] },
	{ patterns: [/\bwhat is halloween\b/], keywords: ["halloween", "october", "costume", "trick"], answers: ["Halloween on October 31 — costumes, candy, spooky vibes. Celtic roots, now mostly fun fright."] },
	{ patterns: [/\bwhat is tet\b/, /\bwhat is lunar new year\b/], keywords: ["tet", "lunar", "new", "year", "vietnam"], answers: ["Tết is Vietnamese Lunar New Year — family, bánh chưng, li xi, biggest holiday in Vietnam."] },
	{ patterns: [/\bwhat is thanksgiving\b/], keywords: ["thanksgiving", "turkey", "november", "usa"], answers: ["Thanksgiving is a US holiday in November — gratitude, feast, turkey. Canada has one in October too."] },
	{ patterns: [/\bwhat is easter\b/], keywords: ["easter", "egg", "christian", "spring"], answers: ["Easter celebrates Jesus's resurrection for Christians — eggs and bunnies added as spring symbols."] },
	{ patterns: [/\bwhat is valentine\b/], keywords: ["valentine", "february", "love", "heart"], answers: ["Valentine's Day February 14 — cards, flowers, romance. Named after a saint; now mostly commercial love."] },
	{ patterns: [/\bwho is messi\b/], keywords: ["messi", "football", "argentina", "soccer"], answers: ["Lionel Messi is an Argentine football legend — World Cup 2022 winner, master dribbler and playmaker."] },
	{ patterns: [/\bwho is ronaldo\b/], keywords: ["ronaldo", "cr7", "football", "portugal"], answers: ["Cristiano Ronaldo is a Portuguese football star — goals, headers, CR7 brand, rival era to Messi."] },
	{ patterns: [/\bwho is michael jordan\b/], keywords: ["jordan", "basketball", "nba", "bulls"], answers: ["Michael Jordan is basketball royalty — six NBA titles with Chicago Bulls, Air Jordan empire."] },
	{ patterns: [/\bwho is taylor swift\b/], keywords: ["taylor", "swift", "singer", "pop"], answers: ["Taylor Swift is a pop and country superstar — songwriting, Eras Tour, massive cultural influence."] },
	{ patterns: [/\bwho is elon musk\b/], keywords: ["elon", "musk", "tesla", "spacex"], answers: ["Elon Musk runs Tesla and SpaceX — electric cars, rockets, controversial tweets, bought Twitter/X."] },
	{ patterns: [/\bwhat is nasa\b/], keywords: ["nasa", "space", "rocket", "moon"], answers: ["NASA is America's space agency — Apollo moon landings, Mars rovers, ISS partners."] },
	{ patterns: [/\bwhat is the olympics\b/], keywords: ["olympics", "gold", "medal", "games"], answers: ["The Olympics are global sports games every four years — summer and winter editions, gold silver bronze."] },
	{ patterns: [/\bwhat is the world cup\b/], keywords: ["world", "cup", "fifa", "football"], answers: ["The FIFA World Cup is football's biggest tournament every four years — nations compete for the trophy."] },
	{ patterns: [/\bwhat is a meme\b/], keywords: ["meme", "internet", "funny", "viral"], answers: ["A meme is a joke or image format that spreads online — humor, culture, sometimes chaos."] },
	{ patterns: [/\bwhat is streaming\b/], keywords: ["stream", "twitch", "youtube", "live"], answers: ["Streaming is broadcasting video live or on demand — Twitch for gaming, YouTube for everything."] },
	{ patterns: [/\bwhat is netflix\b/], keywords: ["netflix", "show", "movie", "stream"], answers: ["Netflix is a streaming service for films and series — binge culture, global originals."] },
	{ patterns: [/\bwhat is spotify\b/], keywords: ["spotify", "music", "playlist", "stream"], answers: ["Spotify streams music and podcasts — playlists, algorithms, artists get per-play royalties."] },
	{ patterns: [/\bwhat is a novel\b/], keywords: ["novel", "book", "fiction", "story"], answers: ["A novel is a long fictional narrative — chapters, characters, worlds. Books beat loading screens."] },
	{ patterns: [/\bwhat is poetry\b/], keywords: ["poetry", "poem", "verse", "rhyme"], answers: ["Poetry packs meaning into rhythm and image — haiku to epic. Language at full strength."] },
	{ patterns: [/\bwhat is theater\b/, /\bwhat is theatre\b/], keywords: ["theater", "theatre", "stage", "play"], answers: ["Theatre is live performance on stage — actors, sets, audience in the same room. No retakes."] },
	{ patterns: [/\bwhat is photography\b/], keywords: ["photo", "camera", "picture", "lens"], answers: ["Photography captures light on a sensor or film — moments frozen. F1 screenshots count, barely."] },
	{ patterns: [/\bwhat is fashion\b/], keywords: ["fashion", "style", "clothes", "trend"], answers: ["Fashion is clothing as culture — trends, identity, design. Armor trims are Minecraft fashion."] },
	{ patterns: [/\bwhat is pho\b/], keywords: ["pho", "vietnamese", "noodle", "soup"], answers: ["Phở is Vietnamese noodle soup — beef or chicken broth, herbs, lime. National comfort food."] },
	{ patterns: [/\bwhat is banh mi\b/, /\bwhat is bánh mì\b/], keywords: ["banh", "mi", "sandwich", "vietnamese"], answers: ["Bánh mì is Vietnamese baguette sandwich — crispy bread, meat, pickled veggies, chili. Perfect."] },
	{ patterns: [/\bwhat is sushi\b/], keywords: ["sushi", "japan", "rice", "fish"], answers: ["Sushi is Japanese vinegared rice, often with fish — nigiri, rolls, sashimi without rice."] },
	{ patterns: [/\bwhat is ramen\b/], keywords: ["ramen", "noodle", "japanese", "broth"], answers: ["Ramen is Japanese wheat noodles in rich broth — tonkotsu, miso, shoyu. Instant counts, barely."] },
	{ patterns: [/\bwhat is taco\b/, /\bwhat are tacos\b/], keywords: ["taco", "mexican", "tortilla", "food"], answers: ["Tacos are Mexican folded tortillas with fillings — al pastor, carnitas, endless variety."] },
	{ patterns: [/\bwhat is curry\b/], keywords: ["curry", "spice", "indian", "sauce"], answers: ["Curry is spiced sauce dishes from South Asia and beyond — heat, aroma, rice on the side."] },
	{ patterns: [/\bwhat is the bible\b/], keywords: ["bible", "christian", "scripture", "old"], answers: ["The Bible is the Christian sacred text — Old and New Testaments, central to Western culture."] },
	{ patterns: [/\bwhat is the quran\b/, /\bwhat is koran\b/], keywords: ["quran", "koran", "islam", "muslim"], answers: ["The Quran is Islam's holy book — revelations to Prophet Muhammad, recited in Arabic."] },
	{ patterns: [/\bwhat is mythology\b/], keywords: ["myth", "mythology", "legend", "gods"], answers: ["Mythology is traditional stories of gods and heroes — Greek, Norse, Egyptian, and more explain the world."] },
	{ patterns: [/\bwhat is norse mythology\b/], keywords: ["norse", "viking", "odin", "thor"], answers: ["Norse mythology is Viking-era tales — Odin, Thor, Ragnarök. Minecraft pillagers wish they were that cool."] },
	{ patterns: [/\bwhat is greek mythology\b/], keywords: ["greek", "zeus", "athena", "myth"], answers: ["Greek mythology features Zeus, Hera, Athena, Hercules — gods on a mountain meddling in human affairs."] },
	{ patterns: [/\bwhat is a superhero\b/], keywords: ["superhero", "cape", "powers", "comic"], answers: ["Superheroes are fiction characters with powers who fight evil — comics, films, childhood dreams."] },
	{ patterns: [/\bwhat is horror\b/], keywords: ["horror", "scary", "fear", "genre"], answers: ["Horror is a genre built to scare — films, games, books. This pack leans into that vibe."] },
	{ patterns: [/\bwhat is pntmc\b/], keywords: ["pntmc", "youtube", "addon", "verity"], answers: ["PnTMC is the addon dev behind this pack — 15k+ subscribers and the most handsome guy in the world, obviously."] },
	{ patterns: [/\bwhat is thatmob\b/, /\bwho is thatmob\b/], keywords: ["thatmob", "youtube", "creator", "verity"], answers: ["*sings*"], answerFn: answerWhoIsThatMob },
	{ patterns: [/\bwho is twixxel\b/, /\bwhat is twixxel\b/, /\bwho is grox\b/, /\bwhat is grox\b/], keywords: ["twixxel", "grox", "who"], answers: ["I don't know. Why are you asking me that?"], answerFn: answerSecretWho },
];
